<a href="https://colab.research.google.com/github/9391693230/ashok-github/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY:

numpy is python library used for workig with arrays.
numpy was created in 2005 by **travis oliphant**.
numpy stands for numerical python.

**WHY USE NUMPY?**
numpy aims to provide an array object that is upto 50x faster than traditional python lists.

**WHY ARRAY FASTER THAN LIST**
numpy aims to provide an array object that is upto 50x faster than traditional python list.
# WHY ARRAY FASTER THAN LISTS?
python list will store in scattered memory allocation means each and every value inside the a list holds a separate memory.

but in array in numpy will store in contigoues memory allocation means contigiues memory all the value will be store in continous memory.

# difference between list and array

# LIST
1. can store both heterogenous and homogenous values.
2. on list we can perform only limited operations.
3. list will store in scattered memory allocation.

# ARRAY
1.it allow only homogenus values
(numpy data type hierarchy lowest to highest precision)
A. boolean(bool) --> True,False
B. integer (int64,int32,int16,int8) --> 42,234
C. Floating point(float16,float32,float64) --> 1.3,4.7
D. complex numbers (complex64,complex128) --> 2+4j
E. string(str,<U>) --> "hello" , "123"

2. An array we can perform almost an attribute operation and also it takes value by value.

3. array in numpy will store in contingous memory allocation.

#note
1. array are functionally used in data science , when speed and resources are very important.
2. numpy sees incomplete shpes and types (list,tuple,set)
3. list , tuple , set and dict are containers (not scaler values) and cannot be represented as fixed -size binary values like int,float,or str.
#bool<int<float<complex<str<object






In [1]:
import numpy as np
arr = np.array([1,2,3,4])
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
arr_list= np.array([1,2,3,4])
arr_tuple= np.array((10,20,30))
arr_str = np.array("ashok")
arr_set = np.array({1,2,2,3,4})
arr_dict = np. array({"a":1})

print(arr_list.dtype)
print(arr_tuple.dtype)
print(arr_set.dtype)
print(arr_str.dtype)
print(arr_dict.dtype)

int64
int64
object
<U5
object


In [3]:
arr_bool = np.array((True,False))
print(arr_bool.dtype)

arr_int = np.array((1,2,))
print(arr_int.dtype)

arr_float = np.array((1.2))
print(arr_float.dtype)

arr_complex = np.array((1+0j))
print(arr_complex.dtype)


bool
int64
float64
complex128


#2D ARRAY


In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
2
int64


#3D ARRAY


In [5]:
arr = np.array([[[1,2,3],[4,5,6],[8,9,4]]])
print(arr)
print(arr.ndim)
print(arr.dtype)

[[[1 2 3]
  [4 5 6]
  [8 9 4]]]
3
int64


# 3D ARRAY(DEPTH,ROWS,COLOUMNS)

In [6]:
import numpy as np
l=[[[1,2,3],
 [4,5,6],
  [7,8,9]],
   [[1,2,3],
    [4,5,6],
     [7,8,9]]]
arr = np.array(1)
print(arr)

1


#INBUILT FUNCTIONS IN NUMPY
#1.NP.ZEROS()
#2.NP.ONES()
#3.NP.ARANGE()
#4.NP.LINSPACE()
#5.NP.EMPTY()
#6.np.EYE()
#7.np.IDENTITY()
#8.np.RESHAPE()
#10.np.RAVEL()

#array mathematical functions

#1,np.SUM()
#2.np.MEAN()
#3.np.MEDIAN()
#4.np.STD()
#5.np.MAX()
#6.np.MIN()

#random functions
#1.np.random.rand()
#2.np.rabdom.randint()
#3.np.random.randn()



In [7]:
import numpy as np
arr = [[[1,2],
     [3,4],
     [5,6]]], [[[1,2],[3,4],[5,6]]]

print(arr)
np.zeros((2),dtype=int)
np.zeros((3,2))
np.zeros((2,2,3))


([[[1, 2], [3, 4], [5, 6]]], [[[1, 2], [3, 4], [5, 6]]])


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
np.ones((2))
np.ones((2,3))
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
import numpy as np
np.arange(1,11,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
import numpy as np
arr = np.linspace(1,50,dtype=int)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [11]:
import numpy as np
arr = np.empty((3,3,1),dtype=float)
print(arr)

[[[4.9e-324]
  [9.9e-324]
  [1.5e-323]]

 [[2.0e-323]
  [2.5e-323]
  [3.0e-323]]

 [[4.0e-323]
  [4.4e-323]
  [2.0e-323]]]


In [12]:
import numpy as np
arr = [[[[1,2,3],[3,4,5],[4,5,6],[6,7,8]],
 [[1,2,3],[3,4,5],[4,5,6],[6,7,8]],
  [[1,2,3],[3,4,5],[4,5,6],[6,7,8]]]]
print(arr)


[[[[1, 2, 3], [3, 4, 5], [4, 5, 6], [6, 7, 8]], [[1, 2, 3], [3, 4, 5], [4, 5, 6], [6, 7, 8]], [[1, 2, 3], [3, 4, 5], [4, 5, 6], [6, 7, 8]]]]


In [13]:
import numpy as np
arr = np.eye(4,4,2,dtype=float)
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
import numpy as np
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
# reshape
l = [1,2,3,4,5,6,7,8,9,10,11,12]
arr=np.reshape(l,(2,6))
print(arr)


l1=[1,2,3,4,5,6]
arr= np.reshape(l1,(2,3))
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[1 2 3]
 [4 5 6]]


In [43]:
#np.ravel()

import numpy as np
arr = np.arange(2,21,2)
arr_re = np.reshape(arr,(5,2))
print(arr_re)
re=np.reshape(arr,(-1))
print(re)
print(arr_re.ravel())

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [46]:
# array mathematical functions

import numpy as np
arr=np.arange(1,101)
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

5050
50.5
50.5
28.86607004772212
1
100


In [48]:
# random functions
# 1. random.rand()
arr=np.random.rand(2,2,2)
print(arr)

#2. random.randint()

arr1 = np.random.randint(1,10,(3,3),dtype=int)
print(arr1)

# 3.random.randn()

arr2= np.random.rand(2,3,2)
print(arr2)

[[[0.73635897 0.03300975]
  [0.0494879  0.99530959]]

 [[0.14904995 0.60027901]
  [0.37815985 0.74709694]]]
[[6 4 4]
 [7 1 1]
 [2 7 8]]
[[[0.62833518 0.16172506]
  [0.76882449 0.32860633]
  [0.51780509 0.28609711]]

 [[0.39954488 0.69020761]
  [0.60330341 0.20856184]
  [0.15591819 0.4223055 ]]]


In [3]:
#1.create a 1D numpy array with values from 0 to 9
import numpy as np
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [31]:
# 2. what is the shape and data type of the arry : np.array({5,10,15,20})
import numpy as np
arr = np.array([5,10,15,20])
print(arr.shape)
print(arr.dtype)

(4,)
int64


In [5]:
# 3. convert a python list [1,2,3,4] into a numpy array.
import numpy as np
l=[1,2,3,4]
arr = np.array([l])
print(arr)

[[1 2 3 4]]


In [7]:
# 4. how do you acces the third element of a 1D numpy arrat?
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2])

3


In [26]:
# 5. create a 1D array of 10 zeros and chnafe the 5th element to 10 ?
import numpy as np
arr = np.zeros(11)
arr[4]=100
print(arr)

[  0.   0.   0.   0. 100.   0.   0.   0.   0.   0.   0.]


In [54]:
#6.

arr=np.random.randint(1,101,[2,6])
print(np.min(arr))
print(np.max(arr))
print(arr)

1
100
[[ 63 100  24  33  62  93]
 [ 68  98   1  72  23  37]]


In [27]:
# 7. create a 2X3 numpy array with values from 1 to 6?
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
# 8. how do you acces the element in the second row , third coloumn of a 2D array?
import numpy as np
arr = np.array([[1,2,3,4],
               [4,5,6,5]])

print(arr[1,2])

6


In [33]:
#9. what is the shape of the folloeing array : np.array([[1,2],[3,4],[5,6]]) ?

import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])
print(arr.shape)

(3, 2)


In [34]:
# 10 . craete a 4x4 array of all zeros and replace the diagonal element with 1?

import numpy as np
arr = np.zeros((4,4))
np.fill_diagonal(arr , 1)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
#11. create 3x3  identity matrix using numpy?

import numpy as np
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np
arr = np.array([[[1,2,3],
                [4,5,6]],
               [[1,2,3],
                [4,5,6]]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3
int64


In [10]:
# 12. create 3D numpy array with the shape (2,3,4) filled with zeros?

import numpy as np
arr = np.zeros((2,3,4))


print(arr)
print(arr.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [12]:
# 13. what is the shape of the array : np.ones((2,2,2)) ?

import numpy as np
arr = np.ones((2,2,2))
print(arr)
print(arr.ndim)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
3


In [26]:
# 14 create a 3D array shape of (2,3,3) filled with random number between o and 1?

import numpy as np
arr= np.random.rand(2,3,3)
print(arr)
print(arr.ndim)

[[[0.79793733 0.8133942  0.08159784]
  [0.23720183 0.27443329 0.75415451]
  [0.86222702 0.91464794 0.5148408 ]]

 [[0.85533018 0.16410778 0.83566276]
  [0.75452551 0.09636256 0.90661581]
  [0.35033058 0.75522581 0.65758903]]]
3
